apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: prd
  template:
    metadata:
      name: {{.environment}}
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/bivas/gitops-control.git
        targetRevision: test
        path: management/environments/{{.environment}}
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
          automated:
            prune: true
            selfHeal: true
