apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: daas-prd-euw1
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: https://github.com/bivas/gitops-control.git
        revision: test
        directories:
          - path: management/environments/prd/euw1/platforms.json
  template:
    metadata:
      name: "prd-euw1-demo-service"
    spec:
      project: default
      source:
        repoURL: https://github.com/bivas/demo-service.git
        targetRevision: HEAD
        path: .meta/units/service/envs/prd/euw1
      destination:
        server: {{.daas-url}}
        namespace: demo-service