apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: daas-prd-euw1
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/bivas/gitops-control.git
              revision: test
              pathParamPrefix: control
              directories:
                - path: management/environments/prd/euw1/daas/*/*
          - git:
              repoURL: https://github.com/bivas/gitops-control.git
              revision: test
              files:
                - path: management/environments/prd/euw1/config/platforms.json
  template:
    metadata:
      name: 'daas-{{index .control.path.segments 5}}-{{index .control.path.segments 6}}'
      labels:
        platform.io/control-plane: daas
    spec:
      project: default
      source:
        repoURL: https://github.com/bivas/gitops-control.git
        targetRevision: test
        path: '{{.control.path.path}}'
      destination:
        server: '{{.daas.url}}'
        namespace: '{{index .control.path.segments 5}}-{{index .control.path.segments 6}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true