apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: daas-prd-euw1
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: https://github.com/bivas/gitops-control.git
        revision: test
        files:
          - path: management/environments/prd/euw1/config/platforms.json
    - git:
        repoURL: https://github.com/bivas/gitops-control.git
        revision: test
        directories:
          - path: "management/environments/prd/euw1/daas/**"
  template:
    metadata:
      name: 'daas-{{index .path.segments 0}}-{{index .path.segments 1}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bivas/gitops-control.git
        targetRevision: test
        path: '{{.path.path}}'
      destination:
        server: '{{.daas.url}}'
        namespace: '{{index .path.segments 0}}-{{index .path.segments 1}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true