apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: daas-prd-euc1
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: https://github.com/bivas/gitops-control.git
        revision: test
        files:
          - path: management/environments/prd/euc1/config/platforms.json
  template:
    metadata:
      name: "prd-euc1-daas"
    spec:
      project: default
      source:
        repoURL: https://github.com/bivas/gitops-control.git
        targetRevision: test
        path: management/environments/prd/euc1/daas
      destination:
        server: '{{.daas.url}}'
        namespace: applications